### Site metadata ###

site_name: Kronos
site_description: Official Kronos Documentation


theme: readthedocs

extra_css: [extra.css]
nav:


  - Start:
    
    - INSTALL: tutorial/install.md
    - MENUS: tutorial/menus.md
    - HELP: tutorial/support.md
    - TIPS: tutorial/tips.md
  
  - Reference:
    - Image Search: tutorial/image_search.md


   
 

  - Obj: tutorial/objects.md
  - Visibility: tutorial/visibility.md
  - Vault: tutorial/animation.md
  - Lighting : tutorial/lighting.md
  - Tidy: tutorial/tidy.md
  - Render: tutorial/render.md
  - Misc: tutorial/misc.md


  - Mesh Menu:
      - Tools: tutorial/meshtools.md
    
  




extra:
  generator: false