### Site metadata ###

site_name: Kronos Docs
site_description: Official Kronos Documentation


theme: readthedocs

extra_css: [extra.css]
nav:


  - Get Started:
    
    - INSTALL: tutorial/installation.md
    - MENU TUTORIAL: tutorial/interfaceandmenus.md
    - SUPPORT: tutorial/support.md
    - TIPS: tutorial/tips.md
  - Operators:
  
    - Object: tutorial/objects.md
    - Visibility: tutorial/visibility.md
    - Lighting : tutorial/lighting.md
    - Animation: tutorial/animation.md
    - Tidy: tutorial/tidy.md
    - Render: tutorial/render.md
    - Misc: tutorial/misc.md

    # - Reference:
    #     - Kiss: tutorial/kiss.md
    
    # - Object:
    #     - Kiss: tutorial/kiss.md

    
    
    # - Graveyard:
    #     - Kiss: tutorial/kiss.md
    
    # - Lighting:
    #     - Kiss: tutorial/kiss.md
    # - Animation:
    #     - Kiss: tutorial/kiss.md
    # - Tidy:
    #     - Kiss: tutorial/kiss.md
    # - Render:
    #     - Kiss: tutorial/kiss.md

    # - Export:
    #     - Kiss: tutorial/kiss.md
    # - Misc:
    #     - Kiss: tutorial/kiss.md
  - Mesh Menu:
      - Tools: tutorial/meshtools.md
    
  - OTHER TOOLS:
      - BLOCKR: tutorial/blockr.md
      - FREEZE: tutorial/freeze.md
  
 
  




extra:
  generator: false