### Site metadata ###

site_name: Kronos
site_description: Kronos Docs


theme: readthedocs

extra_css: [extra.css]
nav:

  - Install: tutorial/install.md
  - Menus: tutorial/menus.md
  - Help: tutorial/support.md
  - Tips: tutorial/tips.md

  - Reference:
    - Image Search: tutorial/image_search.md

  - Obj:
    - Insta Floor: tutorial/insta_floor.md
    - Delete Keep Transform: tutorial/insta_floor.md
  - Visibility: 
    - Find Hidden: tutorial/insta_floor.md
    - Catch Sly Objs: tutorial/insta_floor.md
  - Vault: tutorial/animation.md
   
  - Lighting :
    - HDRI: tutorial/insta_floor.md
    - Reflector: tutorial/insta_floor.md
    - Drop In Light: tutorial/insta_floor.md
    - Toggle Bloom: tutorial/insta_floor.md
  - Tidy: 
    - Batch Rename: tutorial/insta_floor.md
    - Fully Collapse Outliner: tutorial/insta_floor.md
    - Sort Cams Lights: tutorial/insta_floor.md
  - Render:
    - Mark separate: tutorial/insta_floor.md
    - Clear separate: tutorial/insta_floor.md
    - Render Seperate: tutorial/insta_floor.md
    - Render Without GUI: tutorial/insta_floor.md
  - Misc:
    - Open Blend In Explorer: tutorial/open_blend_in_explorer.md
    - Reverse Solidify: tutorial/insta_floor.md


  - Mesh Menu:
    - Tools: tutorial/meshtools.md
    
extra:
  generator: false