### Site metadata ###

site_name: Kronos
site_description: Docs


theme: readthedocs

extra_css: [extra.css]
nav:

  - Install: install.md
  - Menus: menus.md
  - Tips: tips.md
  - Help: support.md

  - Reference:
    - Image search: image_search.md

  - Obj:
    - Insta floor: insta_floor.md
    - Delete keep transform: delete_keep_child_transforms.md
  - Visibility: 
    - Find hidden: find_hidden.md
    - Catch sly objs: catch_sly_objs.md
  - Vault: vault.md
   
  - Lighting :
    - HDRI: hdri.md
    - Reflector: reflector.md
    - Drop in light: drop_in_light.md
    - Toggle bloom: toggle_bloom.md
  - Tidy: 
    - Batch Rename: batch_rename.md
    - Fully Collapse Outliner: fully_collapse_outliner.md
    - Sort cams lights: sort_cams_lights.md
  
  - Render: 
    - Render separate: render_separate.md
    - Render no GUI: render_without_gui.md
 
  - Misc:
    - Open blend in explorer: open_blend_in_explorer.md
    - Reverse solidify: reverse_solidify.md

  - Mesh Menu:
    - Kiss: kiss.md
    - Origin to selected: origin_to_selected.md
    - Fix Transform: fix_transform.md
    - Clean Mode: clean_mode.md
    - Create Shell: create_shell.md
  
  - Bugs List:
    - Bugs List : bugs_list.md  

  - Changelog:
    - Changelog : changelog.md  
extra:
  generator: false

markdown_extensions:
  - attr_list


  