### Site metadata ###

site_name: Kronos
site_description: Official Kronos Documentation


theme: readthedocs

extra_css: [extra.css]
nav:


  # - Start:
    
  - Install: tutorial/install.md
  - Menus: tutorial/menus.md
  - Help: tutorial/support.md
  - Tips: tutorial/tips.md

  - Reference:
    - Image Search: tutorial/image_search.md


   
 

  - Obj: tutorial/objects.md
      - Insta Floor: tutorial/insta_floor.md
      - Delete(Keep Transforms): tutorial/insta_floor.md
  - Visibility: tutorial/visibility.md
    - Find Hidden: tutorial/insta_floor.md
    - Catch Sly Objs: tutorial/insta_floor.md
  - Vault: tutorial/animation.md
    - Vault: tutorial/insta_floor.md
  - Lighting : tutorial/lighting.md
    - HDRI: tutorial/insta_floor.md
    - Reflector: tutorial/insta_floor.md
    - Drop In Light: tutorial/insta_floor.md
    - Toggle Bloom: tutorial/insta_floor.md
  - Tidy: tutorial/tidy.md
    - Batch Rename: tutorial/insta_floor.md
    - Fully Collapse Outliner: tutorial/insta_floor.md
    - Sort Cams/Lights: tutorial/insta_floor.md
  - Render: tutorial/render.md
    - Mark as separate: tutorial/insta_floor.md
    - Clear separate: tutorial/insta_floor.md
    - Render Seperate: tutorial/insta_floor.md
    - Render Without GUI: tutorial/insta_floor.md
  - Misc: tutorial/misc.md
    - Open Blend In Explorer: tutorial/insta_floor.md
    - Reverse Solidify: tutorial/insta_floor.md


  - Mesh Menu:
      - Tools: tutorial/meshtools.md
    
  




extra:
  generator: false