### Site metadata ###

site_name: Kronos Docs
site_description: Official Kronos Documentation


theme: readthedocs

extra_css: [extra.css]
nav:


  - INTRO:
    - GETTING STARTED: tutorial/kronos.md
        

    
    - UI AND MENUS: tutorial/interfaceandmenus.md
  
  - Operators:
  

    - Visibility: tutorial/visibility.md
 
    # - Reference:
    #     - Kiss: tutorial/kiss.md
    
    # - Object:
    #     - Kiss: tutorial/kiss.md

    
    
    # - Graveyard:
    #     - Kiss: tutorial/kiss.md
    
    # - Lighting:
    #     - Kiss: tutorial/kiss.md
    # - Animation:
    #     - Kiss: tutorial/kiss.md
    # - Tidy:
    #     - Kiss: tutorial/kiss.md
    # - Render:
    #     - Kiss: tutorial/kiss.md

    # - Export:
    #     - Kiss: tutorial/kiss.md
    # - Misc:
    #     - Kiss: tutorial/kiss.md
 
    
  - BLOCKR:
      - What is blocker?: tutorial/kiss.md

  
  - Mesh Menu Tools:
      - Kiss: tutorial/kiss.md
  




extra:
  generator: false