### Site metadata ###

site_name: Kronos
site_description: Kronos Docs


theme: readthedocs

extra_css: [extra.css]
nav:

  - Install: tutorial/install.md
  - Menus: tutorial/menus.md
  - Help: tutorial/support.md
  - Tips: tutorial/tips.md

  - Reference:
    - Image Search: tutorial/image_search.md

  - Obj:
    - Insta Floor: tutorial/insta_floor.md
    - Delete Keep Transforms: tutorial/delete_keep_child_transforms.md
  - Visibility: 
    - Find Hidden: tutorial/find_hidden.md
    - Catch Sly Objs: tutorial/catch_sly_objs.md
  - Vault: tutorial/vault.md
   
  - Lighting :
    - HDRI: tutorial/hdri.md
    - Reflector: tutorial/reflector.md
    - Drop In Light: tutorial/drop_in_light.md
    - Toggle Bloom: tutorial/toggle_bloom.md
  - Tidy: 
    - Batch Rename: tutorial/batch_rename.md
    - Fully Collapse Outliner: tutorial/fully_collapse_outliner.md
    - Sort Cams Lights: tutorial/sort_cams_lights.md
  
  - Render: 
    - Render Separate: tutorial/render_separate.md
    - Render No GUI: tutorial/batch_rename.md
 
  
  - Misc:
    - Open Blend In Explorer: tutorial/open_blend_in_explorer.md
    - Reverse Solidify: tutorial/reverse_solidify.md


  - Mesh Menu:
    - Tools: tutorial/meshtools.md
    
extra:
  generator: false