### Site metadata ###

site_name: Kronos
site_description: Kronos Docs


theme: readthedocs

extra_css: [extra.css]
nav:

  - Install: p/install.md
  - Menus: p/menus.md
  - Help: p/support.md
  - Tips: p/tips.md

  - Reference:
    - Image Search: p/image_search.md

  - Obj:
    - Insta Floor: p/insta_floor.md
    - Delete Keep Transforms: p/delete_keep_child_transforms.md
  - Visibility: 
    - Find Hidden: p/find_hidden.md
    - Catch Sly Objs: p/catch_sly_objs.md
  - Vault: p/vault.md
   
  - Lighting :
    - HDRI: p/hdri.md
    - Reflector: p/reflector.md
    - Drop In Light: p/drop_in_light.md
    - Toggle Bloom: p/toggle_bloom.md
  - Tidy: 
    - Batch Rename: p/batch_rename.md
    - Fully Collapse Outliner: p/fully_collapse_outliner.md
    - Sort Cams Lights: p/sort_cams_lights.md
  
  - Render: 
    - Render Separate: p/render_separate.md
    - Render No GUI: p/batch_rename.md
 

  
  - Misc:
    - Open Blend In Explorer: p/open_blend_in_explorer.md
    - Reverse Solidify: p/reverse_solidify.md


  - Mesh Menu:
    - Tools: p/meshtools.md
    
extra:
  generator: false