### Site metadata ###

site_name: Kronos Docs
site_description: Starter template for a MkDocs docs site on GH Pages - including CI
site_url: https://michaelcurrin.github.io/mkdocs-quickstart/

repo_url: https://github.com/MichaelCurrin/mkdocs-quickstart
edit_uri: edit/master/docs/docs

### Build settings ###

theme: readthedocs

extra_css: [extra.css]
nav:
  - Home: 'index.md'
  - 'Kronos':
        - What Is KRONOS?: tutorial/kiss.md
        - INSTALL: tutorial/kiss.md 
        - SUPPORT: tutorial/kiss.md
        - ABOUT: tutorial/kiss.md

  
  - Tutorial:
      - Kiss: tutorial/kiss.md
  - Functions:
      - Kiss: tutorial/kiss.md
extra:
  generator: false